<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="openGL_DSL" nsURI="http://www.example.org/openGL_DSL" nsPrefix="openGL_DSL">
  <eClassifiers xsi:type="ecore:EClass" name="SceneManager">
    <eOperations name="run"/>
    <eOperations name="close"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="WinId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="WinW" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="800"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="WinH" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="600"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="viewport" eType="#//ViewPort"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="camera" eType="#//Camera"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scenes" upperBound="-1"
        eType="#//Scene" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mStop" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="False">
      <eAnnotations/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ViewPort">
    <eOperations name="upload"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xLeft" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="yBolt" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xWidth" eType="#//GLsizei"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="yHeight" eType="#//GLsizei"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Camera">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mEye" eType="#//vec3"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mLook" eType="#//vec3"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mUp" eType="#//vec3"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelViewMat" eType="#//mat4"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mProjMat" eType="#//mat4"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mNearVal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mFarVal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="10000"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Scene">
    <eOperations name="addNode"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Visible" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodo" upperBound="-1" eType="#//Node"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Light" abstract="true" interface="true">
    <eOperations name="uploadL">
      <eParameters name="modelViewMat" eType="#//mat4"/>
    </eOperations>
    <eOperations name="disable"/>
    <eOperations name="enable"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cont" eType="#//GLuint"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="#//GLuint" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="posDIr" eType="#//vec4"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ambient" eType="#//Vector4"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="difusse" eType="#//Vector4"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specular" eType="#//Vector4"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="direccion" eType="#//Vector3"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DirLight" eSuperTypes="#//Light"/>
  <eClassifiers xsi:type="ecore:EClass" name="PosLight" eSuperTypes="#//Light">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kc" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kl" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kq" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SpotLight" eSuperTypes="#//PosLight">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cutoff" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="180"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Node">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="light" upperBound="-1"
        eType="#//Light" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodo" upperBound="-1" eType="#//Node"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="abs_entity" upperBound="-1"
        eType="#//Abs_Entity" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="posicion" eType="#//Vector3"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rotacion" eType="#//Vector3"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="escala" eType="#//Vector3"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Abs_Entity" abstract="true">
    <eOperations name="render">
      <eParameters name="modelViewMat" eType="#//mat4"/>
    </eOperations>
    <eOperations name="upload"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="texture" upperBound="2"
        eType="#//Texture" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="material" eType="#//Material"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mesh" eType="#//Mesh" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Color" eType="#//Vector4"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QuadricEntity" abstract="true" eSuperTypes="#//Abs_Entity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="q" eType="#//GLquadricObj"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Material">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ambient" eType="#//vec4"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="difusse" eType="#//vec4"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="specular" eType="#//vec4"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expF" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="face" eType="#//GLuint"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sh" eType="#//GLuint"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Mesh">
    <eOperations name="mNumVertices" eType="#//GLuint"/>
    <eOperations name="render"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mPrimitive" eType="#//GLuint"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nNumVertices" eType="#//GLuint"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vColors" eType="#//vec4"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vVertices" eType="#//vec3"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vTexCoords" eType="#//vec2"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vNormals" eType="#//vec3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MbR" eSuperTypes="#//IndexMesh">
    <eOperations name="generateIndexMbR" eType="#//MbR">
      <eParameters name="n" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="m" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="perfil" eType="#//vec3"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="n" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="m" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="perfil" eType="#//vec3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Texture">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mWidth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mHeight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IndexMesh" eSuperTypes="#//Mesh">
    <eOperations name="buildNormalVectors"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vIndices" eType="#//GLuint"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nNumIndices" eType="#//GLuint"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="GLsizei" instanceClassName="java.lang.Object"/>
  <eClassifiers xsi:type="ecore:EDataType" name="GLuint" instanceClassName="java.lang.Object"/>
  <eClassifiers xsi:type="ecore:EDataType" name="vec2" instanceClassName="java.lang.Object"/>
  <eClassifiers xsi:type="ecore:EDataType" name="vec3" instanceClassName="java.lang.Object"/>
  <eClassifiers xsi:type="ecore:EDataType" name="vec4" instanceClassName="java.lang.Object"/>
  <eClassifiers xsi:type="ecore:EDataType" name="mat4" instanceClassName="java.lang.Object"/>
  <eClassifiers xsi:type="ecore:EDataType" name="GLquadricObj" instanceClassName="java.lang.Object"/>
  <eClassifiers xsi:type="ecore:EClass" name="EjesRGB" eSuperTypes="#//Abs_Entity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Lenght" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Vector3">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="X" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Z" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PoligonoRegular" eSuperTypes="#//Abs_Entity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="NumVertices" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Radio" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Rellenar" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Vector4">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="R" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="G" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="B" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="A" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rectangulo" eSuperTypes="#//Abs_Entity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Ancho" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Alto" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Rellenar" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Circulo" eSuperTypes="#//Abs_Entity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Radio" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Rellenar" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Esfera" eSuperTypes="#//QuadricEntity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Radio" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cilindro" eSuperTypes="#//QuadricEntity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="RadioBase" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="RadioTope" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Altura" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Disco" eSuperTypes="#//QuadricEntity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="RadioInterno" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="RadioExterno" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiscoParcial" eSuperTypes="#//QuadricEntity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="RadioInterno" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="RadioExterno" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="AnguloInicio" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="AmplitudAngulo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cubo" eSuperTypes="#//Abs_Entity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Lenght" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Toroide" eSuperTypes="#//Abs_Entity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="RadioCentro" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="RadioAnillo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
</ecore:EPackage>
